ALTER TABLE links
    ADD COLUMN IF NOT EXISTS note        VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS click_count BIGINT       NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS max_clicks  INT;
